// ReliefBridge/Models/Models.swift
// Core domain model types for ReliefBridge Insight

import Foundation
import CoreLocation

// MARK: - Carrier

enum CargoCarrier: String, CaseIterable, Identifiable {
    case fedex = "FedEx"
    case ups = "UPS"
    case dhl = "DHL"

    var id: String { rawValue }

    var flightCode: String {
        switch self {
        case .fedex:
            return "FX"
        case .ups:
            return "5X"
        case .dhl:
            return "D0"
        }
    }

    var operationsLabel: String {
        switch self {
        case .fedex:
            return "Memphis-centered express network"
        case .ups:
            return "Louisville-centered air cargo network"
        case .dhl:
            return "Leipzig, Cincinnati, and Hong Kong superhub network"
        }
    }
}

// MARK: - Aircraft

/// Represents a single aircraft in the retrofitted fleet.
struct Aircraft: Identifiable {
    let id: UUID
    let carrier: CargoCarrier
    let flightIdentifier: String
    let tailNumber: String
    let aircraftType: String
    let region: String
    let originCode: String
    let originCity: String
    let originCoordinate: CLLocationCoordinate2D
    let destinationCode: String
    let destinationCity: String
    let destinationCoordinate: CLLocationCoordinate2D
    let scheduledDurationHours: Double
    let routeDistanceKm: Double
    var coordinate: CLLocationCoordinate2D
    var routeProgress: Double
    var isAirborne: Bool
    var healthScore: Double          // 0.0 – 100.0
    var isReliefBridgeEngaged: Bool
    var fuelSavedKg: Double          // projected fuel saved over 1 year (kg)
    var co2AvoidedTons: Double       // projected CO2 avoided over 1 year (metric tons)
}

extension Aircraft {
    var routeLabel: String {
        "\(originCode) → \(destinationCode)"
    }

    var routeSummary: String {
        "\(originCity) to \(destinationCity)"
    }
}

// MARK: - Telemetry

/// A point-in-time snapshot of telemetry data from an aircraft's Edge Controller.
struct TelemetrySnapshot {
    let tailNumber: String
    let timestamp: Date
    var ramAirIntakePressure: Double  // hPa
    var gyroidFlowUniformity: Double  // 0.0 – 1.0 (percentage)
    var jetSheetVelocity: Double      // m/s
    var boundaryLayerRetention: Double // 0.0 – 1.0
    var dragReductionPercent: Double   // 0.0 – 1.0
    var projectedAnnualFuelGainKg: Double
    var dragCoefficientHistory: [DragDataPoint]
}

/// A single data point in the drag coefficient reduction history.
struct DragDataPoint: Identifiable {
    let id: UUID
    let timeElapsed: TimeInterval    // seconds since flight start
    let dragCoefficient: Double
}

// MARK: - Carbon Compliance

/// An immutable, timestamped record of carbon savings generated per flight.
struct LedgerBlock: Identifiable {
    let id: UUID
    let carrier: CargoCarrier
    let timestamp: Date
    let flightIdentifier: String
    let carbonSavedMetricTons: Double // 0.5 – 12.0
    let regulatoryStandard: RegulatoryStandard
    let blockHash: String            // simulated SHA-256 hex string
}

/// The applicable regulatory standard for a carbon ledger entry.
enum RegulatoryStandard: String {
    case corsia = "CORSIA"
    case euEts  = "EU ETS"
}

// MARK: - Financial

/// Financial savings data for a single calendar month.
struct FinancialMonth: Identifiable {
    let id: UUID
    let month: Date
    var fuelSavingsUSD: Double
    var monetizedCarbonCreditsUSD: Double
    var avoidedNoiseFinesUSD: Double
}

// MARK: - Maintenance

/// A predictive maintenance alert generated by the AI analysis engine.
struct MaintenanceAlert: Identifiable {
    let id: UUID
    let carrier: CargoCarrier
    let tailNumber: String
    let flightIdentifier: String
    let affectedComponent: String
    let description: String
    let recommendedAction: String
    let severity: AlertSeverity
    let generatedAt: Date
}

struct CarrierProfile {
    let carrier: CargoCarrier
    let retrofittedAircraftCount: Int
    let annualFuelSavedPerKitKg: Double
    let annualCarbonSavedPerKitTons: Double
    let annualSavingsPerKitUSD: Double
    let quarterlyCarbonTargetTons: Double
    let annualCarbonGoalTons: Double
    let dailyFlightsInScope: Int
    let networkHeadline: String
}

/// The severity level of a maintenance alert.
enum AlertSeverity: Int, Comparable {
    case info     = 0
    case warning  = 1
    case critical = 2

    static func < (lhs: AlertSeverity, rhs: AlertSeverity) -> Bool {
        lhs.rawValue < rhs.rawValue
    }
}

// MARK: - Lattice

/// A zone within the Gyroid Lattice cross-section, with a blockage risk score.
struct LatticeZone: Identifiable {
    let id: UUID
    let zoneLabel: String
    var microPoreBlockageRisk: Double // 0.0 – 1.0
}

// MARK: - KPI

/// A single KPI metric card displayed in the Fleet Command carousel.
struct KPICard: Identifiable {
    let id: UUID
    let title: String
    let value: String
    let unit: String
    let isHealthy: Bool
}
