// ReliefBridgeTests/SimulatedDataServicePropertyTests.swift
// Property-based tests for SimulatedDataService.
// Properties 13 and 14.

import XCTest
import Combine
@testable import ReliefBridge

// MARK: - Property 13: Simulated Ledger Block Value Bounds

// Feature: reliefbridge-insight, Property 13: For any LedgerBlock generated by SimulatedDataService, carbonSavedMetricTons SHALL be in [0.5, 12.0]
// Validates: Requirements 7.4

final class LedgerBlockValueBoundsPropertyTests: XCTestCase {

    /// Property 13: Simulated Ledger Block Value Bounds
    ///
    /// Run SimulatedDataService, collect all ledgerBlocks, verify every
    /// carbonSavedMetricTons ∈ [0.5, 12.0].
    ///
    /// This is a deterministic property test — the seeded data is fixed, so
    /// we verify the invariant holds for every block in the seeded set.
    func testProperty13_LedgerBlockValueBounds() {
        // Feature: reliefbridge-insight, Property 13: For any LedgerBlock generated by SimulatedDataService, carbonSavedMetricTons SHALL be in [0.5, 12.0]
        let sut = SimulatedDataService()

        XCTAssertFalse(sut.ledgerBlocks.isEmpty,
            "SimulatedDataService must seed at least one LedgerBlock")

        var violations: [String] = []
        for block in sut.ledgerBlocks {
            let value = block.carbonSavedMetricTons
            if value < 0.5 || value > 12.0 {
                violations.append(
                    "Block \(block.flightIdentifier): carbonSavedMetricTons = \(value) is outside [0.5, 12.0]"
                )
            }
        }

        XCTAssertTrue(violations.isEmpty,
            "Property 13 violated:\n" + violations.joined(separator: "\n"))
    }

    /// Additional sweep: verify the property holds across multiple independent
    /// service instances (simulating different random seeds / runs).
    func testProperty13_LedgerBlockValueBoundsMultipleInstances() {
        // Feature: reliefbridge-insight, Property 13: For any LedgerBlock generated by SimulatedDataService, carbonSavedMetricTons SHALL be in [0.5, 12.0]
        for iteration in 0..<10 {
            let sut = SimulatedDataService()
            for block in sut.ledgerBlocks {
                let value = block.carbonSavedMetricTons
                XCTAssertGreaterThanOrEqual(value, 0.5,
                    "Iteration \(iteration): Block \(block.flightIdentifier) carbonSavedMetricTons \(value) < 0.5")
                XCTAssertLessThanOrEqual(value, 12.0,
                    "Iteration \(iteration): Block \(block.flightIdentifier) carbonSavedMetricTons \(value) > 12.0")
            }
        }
    }
}

// MARK: - Property 14: Telemetry Update Freshness

// Feature: reliefbridge-insight, Property 14: For any telemetry snapshot published by SimulatedDataService, timestamp SHALL be within 2s of receipt time
// Validates: Requirements 7.2

final class TelemetryUpdateFreshnessPropertyTests: XCTestCase {

    private var cancellables = Set<AnyCancellable>()

    override func tearDown() {
        cancellables.removeAll()
        super.tearDown()
    }

    /// Property 14: Telemetry Update Freshness
    ///
    /// Observe published TelemetrySnapshot values over multiple timer ticks;
    /// verify each timestamp is within 2 seconds of the wall-clock time at receipt.
    func testProperty14_TelemetryUpdateFreshness() {
        // Feature: reliefbridge-insight, Property 14: For any telemetry snapshot published by SimulatedDataService, timestamp SHALL be within 2s of receipt time

        let sut = SimulatedDataService()

        // We need at least one airborne aircraft with telemetry to observe
        XCTAssertFalse(sut.telemetry.isEmpty,
            "SimulatedDataService must seed telemetry for at least one airborne aircraft")

        // Collect (receiptTime, snapshotTimestamp) pairs across multiple ticks
        let expectation = XCTestExpectation(description: "Receive at least 3 telemetry updates")
        expectation.expectedFulfillmentCount = 3

        var violations: [String] = []
        // Allow a small scheduling tolerance on top of the 2s timer interval.
        // The timer fires every 2s; by the time the sink runs and Date() is
        // captured, a few milliseconds of scheduling jitter are expected.
        let maxStalenessSeconds: TimeInterval = 2.5

        sut.$telemetry
            .dropFirst() // skip the initial seeded value
            .sink { telemetryDict in
                let receiptTime = Date()
                for (tailNumber, snapshot) in telemetryDict {
                    let staleness = receiptTime.timeIntervalSince(snapshot.timestamp)
                    if staleness > maxStalenessSeconds || staleness < -maxStalenessSeconds {
                        violations.append(
                            "Tail \(tailNumber): snapshot.timestamp is \(staleness)s from receipt time (limit: ±\(maxStalenessSeconds)s)"
                        )
                    }
                }
                expectation.fulfill()
            }
            .store(in: &cancellables)

        // Wait for 3 timer ticks (each 2s) + generous buffer
        wait(for: [expectation], timeout: 12.0)

        XCTAssertTrue(violations.isEmpty,
            "Property 14 violated:\n" + violations.joined(separator: "\n"))
    }

    /// Verify that the initial seeded telemetry timestamps are also fresh
    /// (within 2 seconds of service creation).
    func testProperty14_InitialTelemetryTimestampsAreFresh() {
        // Feature: reliefbridge-insight, Property 14: For any telemetry snapshot published by SimulatedDataService, timestamp SHALL be within 2s of receipt time
        let beforeInit = Date()
        let sut = SimulatedDataService()
        let afterInit = Date()

        for (tailNumber, snapshot) in sut.telemetry {
            let tooEarly = snapshot.timestamp < beforeInit.addingTimeInterval(-2.0)
            let tooLate  = snapshot.timestamp > afterInit.addingTimeInterval(2.0)
            XCTAssertFalse(tooEarly,
                "Tail \(tailNumber): initial snapshot.timestamp is more than 2s before init")
            XCTAssertFalse(tooLate,
                "Tail \(tailNumber): initial snapshot.timestamp is more than 2s after init")
        }
    }
}
